### ISSUE TITLE
Issue with XS

### ISSUE THREAD

**Issue by egandro** [kpma1985/ansible_proxmox_hetzner#11]
https://github.com/kpma1985/ansible_proxmox_hetzner/blob/515668db71568ac54f9d5105886677f8efb1208a/roles/hetzner_pve/tasks/05_proxmox_post.yml#L46

```yml
- name: PROXMOX post tasks - Run of XS post installer
  ansible.builtin.shell: /tmp/xs-install-post.sh
  args:
    chdir: /tmp # you need to add this in order to allow XS to read the .env file
  register: hetzner_pve_xshock_run
  notify: Restart vmhost
  when: not hetzner_pve_xshock_installed.stat.exists
```
